include: package:lints/recommended.yaml

linter:
  rules:
    sort_constructors_first: false
    prefer_single_quotes: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_final_parameters: true
    always_specify_types: true
    lines_longer_than_80_chars: false
    always_put_required_named_parameters_first: true
    avoid_classes_with_only_static_members: true
    avoid_function_literals_in_foreach_calls: true
    require_trailing_commas: true
    prefer_relative_imports: true
