name: dart_observable
description: A state management library using the Observer pattern, optimized for notifying changes in collections.
version: 1.0.0
repository: https://github.com/rosewareGit/dart_observable/tree/main
issue_tracker: https://github.com/rosewareGit/dart_observable/issues
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.18.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

