name: dart_observable
description: Custom implementation of reactiveX api.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  meta: ^1.9.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
